title: Jack of All Trades
email: pete@laxaltandmciver.co
description: ""
baseurl: "/jack" # the subpath of your site, e.g. /blog
url: "http://laxaltandmciver.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
