---
pages:
- _posts/chicken-the-egg.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: cover
  label: Cover
  type: text
  hidden: false
  default: ''
- name: images
  label: Images
  type: list
  hidden: false
  default: ''
