---
pages:
- _posts/2017-12-21-moment-skis.md
- _posts/deluxe-n-stuff.md
- _posts/2017-12-21-chicken-the-egg.md
- _posts/2017-12-18-carson-dermatology.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: true
  default: project
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: true
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- type: image_gallery
  name: cover
  label: Cover
- type: image_gallery
  name: images
  label: images
